{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "egret-nest.fullname" . }}
  labels: {{- include "egret-nest.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.secretKey }}
  EGRET_NEST_SECRET_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.webhookSecret }}
  EGRET_NEST_WEBHOOK_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.metricsToken }}
  EGRET_NEST_METRICS_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientID }}
  EGRET_NEST_GITHUB_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientSecret }}
  EGRET_NEST_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oidcClientSecret }}
  EGRET_NEST_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
